### ISSUE TITLE
Does not work with WiX Toolset 3.11

### ISSUE THREAD

**Issue by kuenzign** [frederiksen/WixGAExtension#2]
This extension does not work with WiX Toolset 3.11 because it is only set up for 3.10.  Could you please update this to work with the latest version?

**Comment by frederiksen** [comment]
Sure - I will rebuild with a reference to the WiX 3.11 assembly

**Comment by frederiksen** [comment]
Fixed in version 1.2

**Comment by kuenzign** [comment]
Awesome, thanks!
